platform :ios, '13.0'

unless File.respond_to?(:exists?)
  class << File
    alias_method :exists?, :exist?
  end
end

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist..."
  end
  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

pre_install do |installer|
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_swift_pods_swift_version) {}
end

target 'Runner' do
  use_frameworks!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  project_dir = File.dirname(File.realpath(__FILE__))
  flutter_dir = File.join(project_dir, 'Flutter')
  
  # 创建 Flutter.modulemap 让 Xcode 15+ 能找到 Flutter 模块
  modulemap_dir = File.join(project_dir, 'Pods', 'Flutter')
  FileUtils.mkdir_p(modulemap_dir)
  File.write(File.join(modulemap_dir, 'module.modulemap'), <<-MODULE)
framework module Flutter {
  umbrella header "Flutter.h"
  export *
  module * { export * }
}
MODULE
  
  # 复制或链接 Flutter.h
  header_src = File.join(flutter_dir, 'Flutter.framework', 'Headers', 'Flutter.h')
  if File.exist?(header_src)
    FileUtils.cp(header_src, File.join(modulemap_dir, 'Flutter.h')) rescue nil
  end
  
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.0'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
